### PR TITLE
Upgrade to 2018.2 and buildin support for >= go 1.10

### PR DESCRIPTION
**Pull request by czeidler**

### CODE REVIEW

**Comment by asherlporetz** [comment]
You can just use VersionComparatorUtil.compare like here https://github.com/jonestimd/go-lang-idea-plugin/pull/1/files
It will effectively fix https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2918 including in the menu "Preferences | Languages & Frameworks | Go | Go Libraries"

**Comment by czeidler** [comment]
Looks good didn't know about this util. Why is your commit closed and not merged? It seems you fixed some other similar problems in the code as well.
ps. any idea why the tests are failing now?

**Comment by asherlporetz** [comment]
Was trying to fix the failures by simply adjusting the test files according to the expected but they don't make sense (sub element becoming peer element, duplicate parent element, etc.).  Something's off with the parser.

**Comment by czeidler** [comment]
Yes the only test I looked into produced an extra element (I guess for the "<caret>" marker) for which reason the test failed...

**Comment by czeidler** [comment]
I also added some debug support for tests.

**Pull request closed without merging**
